#@TYPE: Machine
#@NAME: muse-pi-pro
#@SOC: Ky X1
#@DESCRIPTION: Machine configuration for MusePi Pro

require include/k1.inc

PREFERRED_PROVIDER_virtual/kernel ?= "linux-muse-pi-pro"
PREFERRED_PROVIDER_virtual/bootloader ?= "u-boot-muse-pi-pro"

KERNEL_DEVICETREE ?= "spacemit/k1-x_MUSE-Pi-Pro.dtb"

UBOOT_MACHINE = "k1_defconfig"

# let u-boot-spl-k1 handle the binary
SPL_BINARY = ""
UBOOT_ENV = "boot"
UBOOT_ENV_SUFFIX = "scr"

RISCV_SBI_PLAT = "generic"

KERNEL_CLASSES = "kernel"
KERNEL_IMAGETYPE = "Image"

EXTRA_IMAGEDEPENDS += "u-boot-muse-pi-pro u-boot-spl-k1"

IMAGE_BOOT_FILES += " \
	${UBOOT_ENV}.${UBOOT_ENV_SUFFIX} \
	k1-x_MUSE-Pi-Pro.dtb \
	${KERNEL_IMAGETYPE} \
	initramfs.img \
	env_k1-x.txt"

INITRAMFS_FSTYPES = "cpio.gz"
IMAGE_FSTYPES += " wic.gz wic.bmap ext4"
IMAGE_CLASSES:append = " muse-pi-pro-image"

WIC_CREATE_EXTRA_ARGS ?= "--no-fstab-update"
WKS_FILE ?= "muse-pi-pro.wks"

SERIAL_CONSOLES = "115200;ttyS0"
MACHINE_FEATURES = "screen keyboard ext2 ext3 serial"
MACHINE_EXTRA_RRECOMMENDS += "kernel-modules"
